export const DUMMY_TASKS = [
  { id: "t1",
      userId: "u1", 
      name: 'Task 1', 
      title: 'Task 1 Title',
      summary: 'Description for Task 1',
      dueDate: '2024-06-30',
    },
     { id: "t2",
      userId: "u1", 
      name: 'Task 1', 
      title: 'Task 1 Title',
      summary: 'Description for Task 1',
      dueDate: '2024-06-30',
    },
     { id: "t3",
      userId: "u1", 
      name: 'Task 1', 
      title: 'Task 1 Title',
      summary: 'Description for Task 1',
      dueDate: '2024-06-30',
    },
];
